### ISSUE TITLE
ModuleNotFoundError: No module named 'nats.aio'; 'nats' is not a package

### ISSUE THREAD

**Issue by Reponic** [nats-io/nats.py#145]
Traceback (most recent call last):
  File "/Users/mv-miguel/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/mv-miguel/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/mv-miguel/Desktop/Socket Example/nats.py", line 2, in <module>
    import nats.aio.client
  File "/Users/mv-miguel/Desktop/Socket Example/nats.py", line 2, in <module>
    import nats.aio.client
ModuleNotFoundError: No module named 'nats.aio'; 'nats' is not a package

Every time that I try to run the example on the read me I keep getting this error. Why?

**Comment by wallyqs** [comment]
Maybe the module is not in the `PYTHONPATH`? Something like: 

```sh
export PYTHONPATH="${PYTHONPATH}:/path/to/nats/module/"
```

**Comment by wallyqs** [comment]
ahh maybe try renaming the `nats.py` to `example.py`

**Comment by Reponic** [comment]
Yeah I rename the file and either

Traceback (most recent call last):
  File "example.py", line 3, in <module>
    from nats.aio.client import Client as NATS
ModuleNotFoundError: No module named 'nats.aio'; 'nats' is not a package

**Comment by charliestrawn** [comment]
What is the output if you list the directory containing your emaple? `ls /Users/mv-miguel/Desktop/Socket Example/` I'm thinking there is still a nats.py file in there that python is looking in to find those imports.

**Comment by wallyqs** [comment]
Closing due to age.
