### ISSUE TITLE
Catching the connect Exception 

### ISSUE THREAD

**Issue by mohsenpashna** [nats-io/nats.py#186]
Hi, 
I have a problem catching the `connect` Exception. When Nat's servers are not available, I am expecting the `connect` throw `ConnectionRefusedError` or `ErrNoServers` Exceptions. It prints these errors even prints `ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 4222)`, but the exception is not catchable. I have tried the examples too, but the same thing happened. Could you please help me with that?

```python
        try:
            await self.nc.connect(servers=["nats://127.0.0.1:4222"], loop=self.loop)
            # await self.nc.connect(servers=["nats://demo.nats.io:4222"], loop=self.loop)
        except ConnectionRefusedError:
            print("ConnectionRefusedError!!!")
        except ErrNoServers:
            print("ErrNoServers!!!")
        except:
            print("ERROR")
```

But here is what it prints in the terminal!

```bash
nats: encountered error
Traceback (most recent call last):
  File "/home/rz/.local/lib/python3.6/site-packages/nats/aio/client.py", line 1185, in _select_next_server
    connection_future, self.options['connect_timeout']
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/lib/python3.6/asyncio/streams.py", line 81, in open_connection
    lambda: protocol, host, port, **kwds)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 794, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.6/asyncio/base_events.py", line 781, in create_connection
    yield from self.sock_connect(sock, address)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 439, in sock_connect
    return (yield from fut)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 469, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 4222)
```

**Comment by charliestrawn** [comment]
Hi @mohsenpashna, it looks like the [default error callback is being triggered](https://github.com/nats-io/nats.py/blob/master/nats/aio/client.py#L131-L136). You can override this callback back by passing in a function of your own as the `error_cb` argument to `connect`. Something like this should do the trick:

```py
def handle_error(err):
    if isinstance(err, ConnectionRefusedError):
        print("ConnectionRefusedError!!!")
    if isinstance(err, ErrNoServers):
        print("ErrNoServers!!!")
    print("ERROR")

await self.nc.connect(servers=["nats://127.0.0.1:4222"], loop=self.loop, error_cb=handle_error)
# await self.nc.connect(servers=["nats://demo.nats.io:4222"], loop=self.loop)
```

Hope that helps!

**Comment by mohsenpashna** [comment]
Thank @charliestrawn It worked! :o)
