### ISSUE TITLE
ConnectionResetError: Connection lost

### ISSUE THREAD

**Issue by yolking** [nats-io/nats.py#198]
Hello, I have specific problem I have no idea why.
I use python script, which uses nats in a very simple way. Every 30 minutes another app sends information by nats in two quite huge messages by two different channels, python receives them, makes it's calculations and sends back reply by another channel. Both .exe are running on a single aws instance and using local nats server. Python script is packed in .exe application.
It works fine until once in long time it suddenly looses connection, I guess. I see such errors in python log:

```
nats: encountered error
Traceback (most recent call last):
  File "nats\aio\client.py", line 1711, in _flusher
  File "asyncio\streams.py", line 387, in drain
  File "asyncio\streams.py", line 190, in _drain_helper
ConnectionResetError: Connection lost
```
According to my logs, python continues to receive messages by one channel but completely looses messages by another channel.
Is there any way how to make sure this doesn't happen or how can I localize the problem? How can find out the exact reason of connection loss?
I have almost identical in logic python script which works perfectly fine, so I think it's some kind of a technical issue related to message size or something.
I think, the easiest way would be to add reconnection with resubscription? Though I don't understand why this can happen in the first place.

**Comment by yolking** [comment]
It seems the problem was caused by AWS instance overload, from which nats couldn't recover. After fixing overloads no more errors. So not really a nats issue.
