### ISSUE TITLE
Auto-decoding data within the client causes errors

### ISSUE THREAD

**Issue by briedel** [nats-io/nats.py#227]
See error:

```
Traceback (most recent call last):
  File "./count_words.py", line 42, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "./count_words.py", line 30, in main
    print(msgs)
  File "/home/briedel/.local/lib/python3.8/site-packages/nats/aio/client.py", line 432, in __repr__
    return f"<{self.__class__.__name__}: subject='{self.subject}' reply='{self.reply}' data='{self.data[:10].decode()}...'>"
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 8-9: unexpected end of data
```
may be better to let users decode the message.

**Comment by wallyqs** [comment]
Fixed via #233
