### ISSUE TITLE
Broken in Python 3.10

### ISSUE THREAD

**Issue by thomassa** [nats-io/nats.py#235]
The latest release (0.11.5) does not work with Python 3.10 (the current Python version).
As described in #197, Python 3.10 has a breaking change in the `asyncio` module.
Until a fixed version of nats.py is released, I suggest changing the pip/PyPi package to specify Python <3.10.

```
Traceback (most recent call last):
  [...some lines (not in nats) omitted...]
  File "/usr/local/lib/python3.10/site-packages/nats/aio/client.py", line 310, in connect
    self._flush_queue = asyncio.Queue(
  File "/usr/local/lib/python3.10/asyncio/queues.py", line 33, in __init__
    super().__init__(loop=loop)
  File "/usr/local/lib/python3.10/asyncio/mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Queue() since it is no longer necessary
```

**Comment by wallyqs** [comment]
Version 2.0.0 has been released so closing, Python 3.10 supported in that version.
