### ISSUE TITLE
Broken examples when run in windows environment without docker

### ISSUE THREAD

**Issue by gitgkk** [nats-io/nats.py#323]
Hi,

I was initially using NATS 2.1.9 and my code worked fine, when I moved to 2.8.4 with python3, the code broke. I checked the example but that doesn't work either, I'm getting the same errors.

**Example: connect.py**
python3 connect.py
Received a message on help.please _INBOX.MNylYLSpOhYT09BRObUHfS.MNylYLSpOhYT09BRObUHiK: b'help'
Response: Msg(_client=<nats client v2.1.3>, subject='_INBOX.MNylYLSpOhYT09BRObUHfS.MNylYLSpOhYT09BRObUHiK', reply='', data=b'OK', headers=None, _metadata=None, _ackd=False)
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000240EB8D98B0>
Traceback (most recent call last):
  File "C:\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Python38\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Python38\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Example: service.py**
python3 service.py
Traceback (most recent call last):
  File "service.py", line 42, in <module>
    loop.run_until_complete(run(loop))
  File "C:\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "service.py", line 13, in run
    await nc.connect("127.0.0.1",
TypeError: connect() got an unexpected keyword argument 'loop'

**Example: advanced.py**
This example worked but when I did not start the server and executed the example, I got "There was an error: ", I was expecting NoServersError. 

**Signal Handling**
The signal handing code threw a NotImplementedError.

Can you please share how to correct and the insight on how a long running service can be built?

**Comment by wallyqs** [comment]
Tried with Python 3.8.13 and seems fine?

```
docker run -v $(pwd):/nats -it python:3.8 /bin/sh 
root@43ae7e8c80cd:/# cd nats/
root@43ae7e8c80cd:/nats# export PYTHONPATH=$(pwd)
root@43ae7e8c80cd:/nats# python3 --version
Python 3.8.13

root@43ae7e8c80cd:/nats# python3 examples/connect.py 
Received a message on help.please _INBOX.OhHqcoEnYnvwYOve2fvnXt.OhHqcoEnYnvwYOve2fvncs: b'help'
Response: Msg(_client=<nats client v2.1.3>, subject='_INBOX.OhHqcoEnYnvwYOve2fvnXt.OhHqcoEnYnvwYOve2fvncs', reply='', data=b'OK', headers=None, _metadata=None, _ackd=False)

root@43ae7e8c80cd:/nats# python3 examples/service.py 
Listening for requests on 'help' subject...
Received a message on 'help _INBOX.ZwNoM286M09bRtoYdTWe1R.ZwNoM286M09bRtoYdTWe4w': hi
Msg(_client=<nats client v2.1.3>, subject='_INBOX.ZwNoM286M09bRtoYdTWe1R.ZwNoM286M09bRtoYdTWe4w', reply='', data=b'I can help', headers=None, _metadata=None, _ackd=False)
```

**Comment by gitgkk** [comment]
Please try this code on windows installation. All the errors are reproducible. I can confirm that I have reinstalled python, nats, nats python client and still the same issues are present.

**Comment by wallyqs** [comment]
Thanks for the information, I was not aware that there might be an incompatibility with `asyncio.run` on windows.  Can you try with replacing `asyncio.run(main())` with `asyncio.get_event_loop().run_until_complete(main())`?

**Comment by gitgkk** [comment]
Hi,
I got these errors after suggested modifications.

nats: encountered error
Traceback (most recent call last):
  File "C:\Python\Python39\lib\asyncio\streams.py", line 52, in open_connection
    transport, _ = await loop.create_connection(
  File "C:\Python\Python39\lib\asyncio\base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "C:\Python\Python39\lib\asyncio\base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Python\Python39\lib\asyncio\selector_events.py", line 500, in sock_connect
    return await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\Python39\lib\asyncio\tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python\Python39\lib\site-packages\nats\aio\client.py", line 1088, in _select_next_server
    r, w = await asyncio.wait_for(
  File "C:\Python\Python39\lib\asyncio\tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
nats: encountered error
Traceback (most recent call last):
  File "C:\Python\Python39\lib\asyncio\streams.py", line 52, in open_connection
    transport, _ = await loop.create_connection(
  File "C:\Python\Python39\lib\asyncio\base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "C:\Python\Python39\lib\asyncio\base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Python\Python39\lib\asyncio\selector_events.py", line 500, in sock_connect
    return await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\Python39\lib\asyncio\tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python\Python39\lib\site-packages\nats\aio\client.py", line 1088, in _select_next_server
    r, w = await asyncio.wait_for(
  File "C:\Python\Python39\lib\asyncio\tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
Traceback (most recent call last):
  File "D:\workspace\se-apps\pysvn-if\svn-server.py", line 117, in <module>
    loop.run_until_complete(run(nats_config))
  File "C:\Python\Python39\lib\asyncio\base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "C:\Python\Python39\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "C:\Python\Python39\lib\asyncio\base_events.py", line 1869, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Python\Python39\lib\selectors.py", line 324, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Python\Python39\lib\selectors.py", line 315, in _select
    r, w, x = select.select(r, w, w, timeout)
KeyboardInterrupt
^C
