### ISSUE TITLE
can not install nats-py on windows

### ISSUE THREAD

**Issue by geoai777** [nats-io/nats.py#348]
python: 3.9.10
nats-py: 2.1.7
virtualenv: 20.13.0

Outside virtualenv with python 3.10.2 nats-py installs with no problem. 
help? 

```python
(venv) natsmq>python -m pip install nats-py --no-cache-dir
Collecting nats-py
  Downloading nats-py-2.1.7.tar.gz (45 kB)
     ---------------------------------------- 45.7/45.7 kB 284.0 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\User\AppData\Local\Temp\pip-install-zitiopno\nats-py_17ba8606a9fa4fb9bac3b1e006af9
7ac\setup.py", line 3, in <module>
          from nats.aio.client import __version__
      ModuleNotFoundError: No module named 'nats'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by geoai777** [comment]
Same issue on python `3.8.10` and `3.7.9`

**Comment by geoai777** [comment]
Fixed it by cloning `nats` to own local git and installing package from there. Hope it helps someone.

**Comment by 15066952332** [comment]
用国内镜像解决了问题
