### ISSUE TITLE
JetStreamContext.add_stream leaves pending asyncio tasks

### ISSUE THREAD

**Issue by orsinium** [nats-io/nats.py#383]
Code to reproduce the issue:

```python
import nats
import nats.js
import pytest


async def run() -> None:
    nc = await nats.connect()
    js = nc.jetstream()
    stream_name = 'stream1'
    config = nats.js.api.StreamConfig(
        name=stream_name,
        subjects=[stream_name],
    )
    await js.add_stream(config)


@pytest.mark.asyncio
async def test_run():
    await run()
```

Commands (I use Python 3.10 but any version should do):

```bash
python3 -m pip install pytest pytest-asyncio
python3 -m pytest tmp.py
```

After the tests finish to run, asyncio spits multiple warnings about pending tasks:

```
Task was destroyed but it is pending!
task: <Task pending name='Task-5' coro=<Client._read_loop() done, defined at /home/gram/.local/lib/python3.10/site-packages/nats/aio/client.py:1959> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-6' coro=<Client._ping_interval() done, defined at /home/gram/.local/lib/python3.10/site-packages/nats/aio/client.py:1942> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Exception ignored in: <coroutine object Client._flusher at 0x7f3db3e2d150>
Traceback (most recent call last):
  File "/home/gram/.local/lib/python3.10/site-packages/nats/aio/client.py", line 1924, in _flusher
    future: asyncio.Future = await self._flush_queue.get()
  File "/usr/lib/python3.10/asyncio/queues.py", line 161, in get
    getter.cancel()  # Just in case getter is not done yet.
  File "/usr/lib/python3.10/asyncio/base_events.py", line 750, in call_soon
    self._check_closed()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Task was destroyed but it is pending!
task: <Task pending name='Task-7' coro=<Client._flusher() done, defined at /home/gram/.local/lib/python3.10/site-packages/nats/aio/client.py:1912> wait_for=<Future cancelled>>
Exception ignored in: <coroutine object Subscription._wait_for_msgs at 0x7f3db3e2d230>
Traceback (most recent call last):
  File "/home/gram/.local/lib/python3.10/site-packages/nats/aio/subscription.py", line 285, in _wait_for_msgs
    msg = await self._pending_queue.get()
  File "/usr/lib/python3.10/asyncio/queues.py", line 161, in get
    getter.cancel()  # Just in case getter is not done yet.
  File "/usr/lib/python3.10/asyncio/base_events.py", line 750, in call_soon
    self._check_closed()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Task was destroyed but it is pending!
task: <Task pending name='Task-8' coro=<Subscription._wait_for_msgs() done, defined at /home/gram/.local/lib/python3.10/site-packages/nats/aio/subscription.py:276> wait_for=<Future cancelled>>
```

It says that it concerns tasks defined for coroutines Subscription._wait_for_msgs, Client._ping_interval, and Client._flusher. As an example, this is the traceback to the places where the task for Subscription._wait_for_msgs is started:

```
tmp.py:14: in run
    await js.add_stream(config)
../../.local/lib/python3.10/site-packages/nats/js/manager.py:89: in add_stream
    resp = await self._api_request(
../../.local/lib/python3.10/site-packages/nats/js/manager.py:260: in _api_request
    msg = await self._nc.request(req_subject, req, timeout=timeout)
../../.local/lib/python3.10/site-packages/nats/aio/client.py:907: in request
    msg = await self._request_new_style(
../../.local/lib/python3.10/site-packages/nats/aio/client.py:926: in _request_new_style
    await self._init_request_sub()
../../.local/lib/python3.10/site-packages/nats/aio/client.py:871: in _init_request_sub
    await self.subscribe(
../../.local/lib/python3.10/site-packages/nats/aio/client.py:845: in subscribe
    sub._start(self._error_cb)
../../.local/lib/python3.10/site-packages/nats/aio/subscription.py:191
    self._wait_for_msgs_task = asyncio.get_running_loop().create_task(
        self._wait_for_msgs(error_cb)
    )
```

You can also see the warnings without using pytest-asyncio if you run the asyncio loop with debug mode enabled:

```python
if __name__ == '__main__':
    loop = asyncio.new_event_loop()
    loop.set_debug(True)
    loop.run_until_complete(run())
```

**Comment by orsinium** [comment]
Shame on me, I just don't close the nats connection >.< Well, it's good to have it here anyway, for posterity.
