### ISSUE TITLE
find_stream_name_by_subject with unknown subject throws exception instead of returning Nonw

### ISSUE THREAD

**Issue by SiriKothe1** [nats-io/nats.py#438]
When I call find_stream_name_by_subject in jetstream with a subject that is not present, I expect it to return None. But it throws an exception as below:
```
import asyncio
import nats

async def main():
    nc = await nats.connect("nats://demo.nats.io:4222")
    js = nc.jetstream()
    stream = await js.find_stream_name_by_subject("some_subject")

if __name__ == "__main__":
    asyncio.run(main())
```

Throws the following exception:
```
Traceback (most recent call last):
  File "t.py", line 12, in <module>
    asyncio.run(main())
  File "/Users/sirikothe/.pyenv/versions/3.7.4/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/Users/sirikothe/.pyenv/versions/3.7.4/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "t.py", line 9, in main
    stream = await js.find_stream_name_by_subject("some_subject")
  File "/Users/sirikothe/.pyenv/versions/3.7.4/lib/python3.7/site-packages/nats/js/manager.py", line 65, in find_stream_name_by_subject
    return info['streams'][0]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by wallyqs** [comment]
Fixed via #512
