### ISSUE TITLE
Jetstream no available responders

### ISSUE THREAD

**Issue by pitwegner** [nats-io/nats.py#530]
### Observed behavior

When setting an `inbox_prefix` in `client.connect` and authorization enabled, I cannot create a stream.

### Expected behavior

I expect the stream to be created successfully.

### Server and client version

NATS 2.10.10

### Steps to reproduce

nats-server.conf
```
authorization {
  TEST: {
    publish: ["$JS.API.STREAM.CREATE.*"]
    subscribe: ["_INBOX_smth.>"]
  }
  users: [
    {user: test, password: test, permissions: $TEST}
  ]
}
```

python script
```python
import asyncio
from nats.aio.client import Client as NATS

async def main():
    nc = NATS()
    await nc.connect(
        'nats://localhost:4222',
        user='test',
        password='test',
        inbox_prefix=b'_INBOX_smth'
    )
    js = nc.jetstream()
    await js.add_stream(name='document', subjects=['foo'])

if __name__ == '__main__':
    asyncio.run(main())
```

python traceback:
```
Traceback (most recent call last):
  File "<redacted>/nats-test/venv/lib/python3.11/site-packages/nats/js/manager.py", line 375, in _api_request
    msg = await self._nc.request(req_subject, req, timeout=timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<redacted>/nats-test/venv/lib/python3.11/site-packages/nats/aio/client.py", line 996, in request
    raise errors.NoRespondersError
nats.errors.NoRespondersError: nats: no responders available for request
```

Observed Server Logs:
```
[TRC] 192.168.65.1:21108 - cid:5 - <<- [SUB _INBOX_smth.bwnjzIRv370GCZUyBF4Ijf.*  1]
[TRC] 192.168.65.1:21108 - cid:5 - <<- [PUB $JS.API.STREAM.CREATE.document _INBOX_smth.bwnjzIRv370GCZUyBF4Ijf.bwnjzIRv370GCZUyBF4IlLda5a 249]
[TRC] 192.168.65.1:21108 - cid:5 - <<- MSG_PAYLOAD: ["{\"name\": \"document\", \"subjects\": [\"foo\"], \"discard\": \"old\", \"max_msgs_per_subject\": -1, \"max_msg_size\": -1, \"no_ack\": false, \"duplicate_window\": 0, \"sealed\": false, \"deny_delete\": false, \"deny_purge\": false, \"allow_rollup_hdrs\": false, \"max_age\": 0}"]
[DBG] 192.168.65.1:21108 - cid:5 - Client connection closed: Client Closed
[TRC] 192.168.65.1:21108 - cid:5 - <-> [DELSUB 1]
```

**Comment by pitwegner** [comment]
Sorry, own stupidity. I was overriding my EXTRA_ARGS env var for debug logs and so the `-js` flag was not applied and thus jet stream not enabled.
